### ISSUE TITLE
[client] 리팩토링 및 개선

### ISSUE THREAD

**Issue by lucy0701** [Mong-Bit/mongbit_fe_next_v2#29]
### containers / view[ Latest, Total ]MbtiTest 컴포넌트 통합 관련
* 현재 containers/ viewLatestMbtiTest, viewTotalMbtiTest 컴포넌트 사용

**분리 한 이유**
  - 가독성
  - 유지보수 시, 통일성
  - 확장성 : 각 뷰페이지에서 서로 다른 기능 추가 될 경우
----
1. 가독성
  - 분리했을 때, 어떤 부분에서 가독성이 좋다는건지 모르겠습니다. (설명 필요)
2. 유지보수 
  - 각 view 컴포넌트에서 동일하게 사용하고 있는 코드를 수정 할 경우, 두 개의 컴포넌트를 수정해야하니 오히려 불편한 것 아닌가 라는 생각입니다.
3. 확장성
  - 두 개 모두 비슷한 기능이 확장 될 것으로 예상됩니다. Ex) 카테고리 분류, 검색 기능등
  - 통합 후, 하나의 컴포넌트로 처리하는게 확장성 면에서 유리 할 것으로 예상

----
* 현재 두개 컴포넌트의 차이점인 '페이징'을 제외하면 동일하게 구현되어 있습니다 (디자인 등등)
* 페이징의 경우, 최신 목록개수 이상일 경우에만 표시 되기 때문에 무관할것 같습니다
* 만약, 컴포넌트 확장 할 경우, 서로 다른 기능이 많이 추가 된다고 하면 그때 처리하는것은 어떨 까요?

**Comment by Moorisong** [comment]
네 동의합니다 기능이 확장돼도 비슷하게 기능이 들어갈가같네뇨. 그렇게 하는게.좋을것같아요

**Comment by Moorisong** [comment]
아 그리거 가독성이나 유지보수 이야기는 
페이지 당 해당 컴퍼넌트로 쪼개져 있는 체계를 유지하고 싶었던 거얐습니다!
