### ISSUE TITLE
[client] add List Component 

### ISSUE THREAD

**Issue by lucy0701** [Mong-Bit/mongbit_fe_next_v2#30]
**List 사용 Components**
* viewTotalMbtiTest
* viewLatestMbtiTest
* viewMyPage

**현재 리스트 관련 Styled component 인 <MbtiTestForViewPage /> 사용 중**
  - 확장성 X, 리스트 내용인 TestCard가 한정되어 있어 MyPage에서 사용 불가

**컴포넌트 재 사용을 위한 컴포넌트 분리**
1. List Component 생성
2. 각 Item 컴포넌트 생성 (ex. test : 테스트 카드, myPage : 결과 카드 등 )

**장점**
- 컴포넌트가 분리 되어있어, 유지 보수 및 확장성 좋음 (새로운 리스트가 추가 되더라도 내용이 담긴 Component만 생성하면 됨)

- Styled Component 적용 : List Component의 Style 구성에 대해 의견있으시면 요청 바람
  - 개인적으론 flex 설정관련 및 배경 컬러 정도만 생각 합니다.

**My Page와 함께 진행 하도록 하겠습니다**

**Comment by Moorisong** [comment]
오 너무 좋은 생각이에요. 이견 없습니다!

**Comment by lucy0701** [comment]
[ 추가 변경 사항 ] 
* Item List Component를 생성 시 단점 
  * 필요없는 프롭 전달이 계속 발생 ( 데이터 및 리스트에서 사용 할 Item Components )
* 하나의 List 컴포넌트를 만들고 사용하는 것이 아닌, 필요에따라 List 생성 ( 기존 방법 동일 )
* 확장성을 생각 했으나 오히려.. 너무 잘게 쪼개 버렸네요..

* 기본 방법과 동일하지만, 더 보기나 무한스크롤을 따로 분리해서 사용하는 것이 좋을것 같습니다 :-)
* 더 보기 같은경우, Total Test List, comment 등에서 사용 하고 있고, 사용처는 계속 생길것 같아요 (카테고리별 더보기 등등)
* 더 보기는 이미 적용되어 있으므로 천천히 바꿔요!

**Comment by lucy0701** [comment]
useInfiniteScroll 생성 완료 -
